# Generated by Django 2.2.4 on 2019-11-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='story_highlights', to='insta.Story'),
        ),
        migrations.AddField(
            model_name='user',
            name='save_post',
            field=models.ManyToManyField(blank=True, related_name='story_highlights', to='insta.Post'),
        ),
    ]
