# Generated by Django 2.2.4 on 2019-11-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20191119_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='save_post',
            field=models.ManyToManyField(blank=True, related_name='story_post', to='insta.Post'),
        ),
    ]
