# Generated by Django 2.2.4 on 2019-11-16 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='creator',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='story', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
