# Generated by Django 2.2.4 on 2019-11-19 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20191119_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_people',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_people',
            field=models.ManyToManyField(blank=True, related_name='tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
